version: "3.8"

services:
  ssv:
    build: .
    working_dir: /app
    environment:
      BITCOIN_RPCUSER: ${BITCOIN_RPCUSER:-ssv}
      BITCOIN_RPCPASS: ${BITCOIN_RPCPASS:-ssvpass}
      BITCOIN_RPCPORT: ${BITCOIN_RPCPORT:-18443}
      BITCOIN_P2PPORT: ${BITCOIN_P2PPORT:-18444}
      BITCOIN_ZMQ_BLOCK: ${BITCOIN_ZMQ_BLOCK:-28332}
      BITCOIN_ZMQ_TX: ${BITCOIN_ZMQ_TX:-28333}
    ports:
      - "18443:18443"
      - "18444:18444"
      - "28332:28332"
      - "28333:28333"
    volumes:
      - ./:/app
      - bitcoin-data:/data/bitcoin
    tty: true
    stdin_open: true

volumes:
  bitcoin-data:
    driver: local
